apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: amf-5g-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: telco-5g-core
  source:
    repoURL: https://github.com/josepbada/5g-gitops-repo.git
    targetRevision: HEAD
    path: charts/amf-5g
    helm:
      valueFiles:
        - ../../environments/dev/amf-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: telco-core-5g
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  # ignoreDifferences:
  #   - group: apps
  #     kind: Deployment
  #     jsonPointers:
  #       - /spec/replicas