apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 5g-upf-green
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/josepbada/5g-gitops-repo.git
    targetRevision: main
    path: helm-charts/5g-upf
    helm:
      valueFiles:
        - ../../environments/dev/upf-values-dev-green.yaml
      releaseName: upf-green
  destination:
    server: https://kubernetes.default.svc
    namespace: telco-5g
  syncPolicy:
    automated:
      prune: false  # Don't auto-prune green initially
      selfHeal: true
    syncOptions:
      - CreateNamespace=true