apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 5g-upf-staging
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/josepbada/5g-gitops-repo.git
    targetRevision: main
    path: helm-charts/5g-upf
    helm:
      valueFiles:
        - ../../environments/staging/upf-values-staging.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: telco-5g-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNameJContinuarspace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m