apiVersion: v1
kind: ConfigMap
metadata:
  name: nrf-config
  namespace: open5gs
  labels:
    app: nrf
    component: control-plane
    deployment-phase: day0-foundation
data:
  nrf.yaml: |
    logger:
      level: info

    nrf:
      sbi:
          - address: 0.0.0.0
            port: 7777

      
      metrics:
          - address: 0.0.0.0
            port: 9090