apiVersion: v1
kind: ConfigMap
metadata:
  name: upf-config
  namespace: open5gs
  labels:
    app: upf
    component: user-plane
    deployment-phase: day0-userplane
data:
  upf.yaml: |
    logger:
      level: info
    
    upf:
      pfcp:
        - addr: 10.100.52.20
      
      gtpu:
        - addr: 10.100.51.20
      
      subnet:
        - addr: 10.45.0.0/16
          dnn: internet
          dev: ogstun