apiVersion: v1
kind: Service
metadata:
  name: {{ include "5g-upf.fullname" . }}
  labels:
    {{- include "5g-upf.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
    protocol: {{ .Values.service.protocol }}
    name: n3-interface
  selector:
    {{- include "5g-upf.selectorLabels" . | nindent 4 }}