{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "amf-5g.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "amf-5g.labels" . | nindent 4 }}
    app: amf-5g
spec:
  podSelector:
    matchLabels:
      {{- include "amf-5g.selectorLabels" . | nindent 6 }}
      app: amf-5g
  policyTypes:
    {{- toYaml .Values.networkPolicy.policyTypes | nindent 4 }}
  ingress:
    {{- toYaml .Values.networkPolicy.ingress | nindent 4 }}
  egress:
    {{- toYaml .Values.networkPolicy.egress | nindent 4 }}
{{- end }}