apiVersion: v1
kind: Service
metadata:
  name: {{ include "amf-5g.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "amf-5g.labels" . | nindent 4 }}
    app: amf-5g
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.ngapPort }}
    targetPort: ngap
    protocol: TCP
    name: ngap
  - port: {{ .Values.service.httpPort }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    {{- include "amf-5g.selectorLabels" . | nindent 4 }}
    app: amf-5g