apiVersion: v1
kind: ConfigMap
metadata:
  name: smf-config
  namespace: telco-core
  labels:
    app: smf
    component: control-plane
data:
  smf.yaml: |
    db_uri: mongodb://mongodb-service:27017/open5gs
    logger:
      level: info
    smf:
      sbi:
        - addr: 0.0.0.0
          port: 7777
      pfcp:
        - addr: 0.0.0.0
      gtpc:
        - addr: 0.0.0.0
      gtpu:
        - addr: 0.0.0.0
      subnet:
        - addr: 10.45.0.1/16
          dnn: internet
      dns:
        - 8.8.8.8
        - 8.8.4.4
      mtu: 1400
      smf_name: SMF